### ISSUE TITLE
Use WPILib's provided Notifier instead of Thread

### ISSUE THREAD

**Issue by iwei20** [StuyPulse/StuyLib#14]
https://github.com/StuyPulse/StuyLib/blob/3b0677c4374507f383e0cd298df828ae62a5e6bd/src/com/stuypulse/stuylib/streams/PollingIStream.java#L15

I think Notifier is more in line to what we've used before, according to Tahsin.

**Comment by Sam-Belliveau** [comment]
we are here to minimize WPI dependencies because of there tenancy to update stuff, breaking a lot of our code. It is not that hard in this case just to bite the bullet.
