### ISSUE TITLE
Is it safe to start the thread(Notifier) in the constructor?

### ISSUE THREAD

**Issue by iwei20** [StuyPulse/StuyLib#15]
https://github.com/StuyPulse/StuyLib/blob/3b0677c4374507f383e0cd298df828ae62a5e6bd/src/com/stuypulse/stuylib/streams/PollingIStream.java#L44

Title.

**Comment by Sam-Belliveau** [comment]
no.

but lets pretend it is.

> ok so basically the problem is is that the thread code will start running before the entire object is constructed which can cause an issue but because of the simplicity of this object I think its going to be ok...
